// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lrc_sampler_cpp
List lrc_sampler_cpp(NumericMatrix X, NumericVector y, IntegerVector src, IntegerVector status, NumericVector logC, List cutpoints, List hyper, List control);
RcppExport SEXP _lrcbart_lrc_sampler_cpp(SEXP XSEXP, SEXP ySEXP, SEXP srcSEXP, SEXP statusSEXP, SEXP logCSEXP, SEXP cutpointsSEXP, SEXP hyperSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type status(statusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type logC(logCSEXP);
    Rcpp::traits::input_parameter< List >::type cutpoints(cutpointsSEXP);
    Rcpp::traits::input_parameter< List >::type hyper(hyperSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(lrc_sampler_cpp(X, y, src, status, logC, cutpoints, hyper, control));
    return rcpp_result_gen;
END_RCPP
}
// predict_forest_cpp
List predict_forest_cpp(List draws, NumericMatrix Xnew);
RcppExport SEXP _lrcbart_predict_forest_cpp(SEXP drawsSEXP, SEXP XnewSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type draws(drawsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xnew(XnewSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_forest_cpp(draws, Xnew));
    return rcpp_result_gen;
END_RCPP
}
// forest_gvar_cpp
NumericVector forest_gvar_cpp(List draws, NumericMatrix Xnew, NumericVector tau0sq, NumericVector tau1sq);
RcppExport SEXP _lrcbart_forest_gvar_cpp(SEXP drawsSEXP, SEXP XnewSEXP, SEXP tau0sqSEXP, SEXP tau1sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type draws(drawsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xnew(XnewSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau0sq(tau0sqSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau1sq(tau1sqSEXP);
    rcpp_result_gen = Rcpp::wrap(forest_gvar_cpp(draws, Xnew, tau0sq, tau1sq));
    return rcpp_result_gen;
END_RCPP
}
// cg_montecarlo_cpp
double cg_montecarlo_cpp(NumericMatrix X, List cutpoints, double alpha, double beta, int nsim, int maxdepth);
RcppExport SEXP _lrcbart_cg_montecarlo_cpp(SEXP XSEXP, SEXP cutpointsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP nsimSEXP, SEXP maxdepthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type cutpoints(cutpointsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type maxdepth(maxdepthSEXP);
    rcpp_result_gen = Rcpp::wrap(cg_montecarlo_cpp(X, cutpoints, alpha, beta, nsim, maxdepth));
    return rcpp_result_gen;
END_RCPP
}
// f_leaf_logmarg_cpp
double f_leaf_logmarg_cpp(double n1, double n2, double s1, double s2, double sig1sq, double sig2sq, double lam2);
RcppExport SEXP _lrcbart_f_leaf_logmarg_cpp(SEXP n1SEXP, SEXP n2SEXP, SEXP s1SEXP, SEXP s2SEXP, SEXP sig1sqSEXP, SEXP sig2sqSEXP, SEXP lam2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< double >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< double >::type sig1sq(sig1sqSEXP);
    Rcpp::traits::input_parameter< double >::type sig2sq(sig2sqSEXP);
    Rcpp::traits::input_parameter< double >::type lam2(lam2SEXP);
    rcpp_result_gen = Rcpp::wrap(f_leaf_logmarg_cpp(n1, n2, s1, s2, sig1sq, sig2sq, lam2));
    return rcpp_result_gen;
END_RCPP
}
// g_leaf_logmarg_cpp
double g_leaf_logmarg_cpp(double n1, double s1, double sig1sq, double tau0sq, double tau1sq, double w);
RcppExport SEXP _lrcbart_g_leaf_logmarg_cpp(SEXP n1SEXP, SEXP s1SEXP, SEXP sig1sqSEXP, SEXP tau0sqSEXP, SEXP tau1sqSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< double >::type sig1sq(sig1sqSEXP);
    Rcpp::traits::input_parameter< double >::type tau0sq(tau0sqSEXP);
    Rcpp::traits::input_parameter< double >::type tau1sq(tau1sqSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(g_leaf_logmarg_cpp(n1, s1, sig1sq, tau0sq, tau1sq, w));
    return rcpp_result_gen;
END_RCPP
}
// g_leaf_pspike_cpp
double g_leaf_pspike_cpp(double n1, double s1, double sig1sq, double tau0sq, double tau1sq, double w);
RcppExport SEXP _lrcbart_g_leaf_pspike_cpp(SEXP n1SEXP, SEXP s1SEXP, SEXP sig1sqSEXP, SEXP tau0sqSEXP, SEXP tau1sqSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< double >::type sig1sq(sig1sqSEXP);
    Rcpp::traits::input_parameter< double >::type tau0sq(tau0sqSEXP);
    Rcpp::traits::input_parameter< double >::type tau1sq(tau1sqSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(g_leaf_pspike_cpp(n1, s1, sig1sq, tau0sq, tau1sq, w));
    return rcpp_result_gen;
END_RCPP
}
// g_leaf_draw_cpp
List g_leaf_draw_cpp(double n1, double s1, double sig1sq, double tau0sq, double tau1sq, double w, int ndraw);
RcppExport SEXP _lrcbart_g_leaf_draw_cpp(SEXP n1SEXP, SEXP s1SEXP, SEXP sig1sqSEXP, SEXP tau0sqSEXP, SEXP tau1sqSEXP, SEXP wSEXP, SEXP ndrawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< double >::type sig1sq(sig1sqSEXP);
    Rcpp::traits::input_parameter< double >::type tau0sq(tau0sqSEXP);
    Rcpp::traits::input_parameter< double >::type tau1sq(tau1sqSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type ndraw(ndrawSEXP);
    rcpp_result_gen = Rcpp::wrap(g_leaf_draw_cpp(n1, s1, sig1sq, tau0sq, tau1sq, w, ndraw));
    return rcpp_result_gen;
END_RCPP
}
// update_tau0_cpp
NumericVector update_tau0_cpp(NumericVector theta, IntegerVector z, double nu0, double s0sq, double tau1sq, int ndraw);
RcppExport SEXP _lrcbart_update_tau0_cpp(SEXP thetaSEXP, SEXP zSEXP, SEXP nu0SEXP, SEXP s0sqSEXP, SEXP tau1sqSEXP, SEXP ndrawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type nu0(nu0SEXP);
    Rcpp::traits::input_parameter< double >::type s0sq(s0sqSEXP);
    Rcpp::traits::input_parameter< double >::type tau1sq(tau1sqSEXP);
    Rcpp::traits::input_parameter< int >::type ndraw(ndrawSEXP);
    rcpp_result_gen = Rcpp::wrap(update_tau0_cpp(theta, z, nu0, s0sq, tau1sq, ndraw));
    return rcpp_result_gen;
END_RCPP
}
// update_tau1_cpp
NumericVector update_tau1_cpp(NumericVector theta, IntegerVector z, double nu1, double s1sq, double tau0sq, int ndraw);
RcppExport SEXP _lrcbart_update_tau1_cpp(SEXP thetaSEXP, SEXP zSEXP, SEXP nu1SEXP, SEXP s1sqSEXP, SEXP tau0sqSEXP, SEXP ndrawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type nu1(nu1SEXP);
    Rcpp::traits::input_parameter< double >::type s1sq(s1sqSEXP);
    Rcpp::traits::input_parameter< double >::type tau0sq(tau0sqSEXP);
    Rcpp::traits::input_parameter< int >::type ndraw(ndrawSEXP);
    rcpp_result_gen = Rcpp::wrap(update_tau1_cpp(theta, z, nu1, s1sq, tau0sq, ndraw));
    return rcpp_result_gen;
END_RCPP
}
// update_w_cpp
NumericVector update_w_cpp(IntegerVector z, double aw, double bw, int ndraw);
RcppExport SEXP _lrcbart_update_w_cpp(SEXP zSEXP, SEXP awSEXP, SEXP bwSEXP, SEXP ndrawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type aw(awSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< int >::type ndraw(ndrawSEXP);
    rcpp_result_gen = Rcpp::wrap(update_w_cpp(z, aw, bw, ndraw));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm_lower_cpp
NumericVector rtnorm_lower_cpp(double mu, double sigma, double a, int n);
RcppExport SEXP _lrcbart_rtnorm_lower_cpp(SEXP muSEXP, SEXP sigmaSEXP, SEXP aSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm_lower_cpp(mu, sigma, a, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lrcbart_lrc_sampler_cpp", (DL_FUNC) &_lrcbart_lrc_sampler_cpp, 8},
    {"_lrcbart_predict_forest_cpp", (DL_FUNC) &_lrcbart_predict_forest_cpp, 2},
    {"_lrcbart_forest_gvar_cpp", (DL_FUNC) &_lrcbart_forest_gvar_cpp, 4},
    {"_lrcbart_cg_montecarlo_cpp", (DL_FUNC) &_lrcbart_cg_montecarlo_cpp, 6},
    {"_lrcbart_f_leaf_logmarg_cpp", (DL_FUNC) &_lrcbart_f_leaf_logmarg_cpp, 7},
    {"_lrcbart_g_leaf_logmarg_cpp", (DL_FUNC) &_lrcbart_g_leaf_logmarg_cpp, 6},
    {"_lrcbart_g_leaf_pspike_cpp", (DL_FUNC) &_lrcbart_g_leaf_pspike_cpp, 6},
    {"_lrcbart_g_leaf_draw_cpp", (DL_FUNC) &_lrcbart_g_leaf_draw_cpp, 7},
    {"_lrcbart_update_tau0_cpp", (DL_FUNC) &_lrcbart_update_tau0_cpp, 6},
    {"_lrcbart_update_tau1_cpp", (DL_FUNC) &_lrcbart_update_tau1_cpp, 6},
    {"_lrcbart_update_w_cpp", (DL_FUNC) &_lrcbart_update_w_cpp, 4},
    {"_lrcbart_rtnorm_lower_cpp", (DL_FUNC) &_lrcbart_rtnorm_lower_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_lrcbart(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
