# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lrc_sampler_cpp <- function(X, y, src, status, logC, cutpoints, hyper, control) {
    .Call(`_lrcbart_lrc_sampler_cpp`, X, y, src, status, logC, cutpoints, hyper, control)
}

predict_forest_cpp <- function(draws, Xnew) {
    .Call(`_lrcbart_predict_forest_cpp`, draws, Xnew)
}

forest_gvar_cpp <- function(draws, Xnew, tau0sq, tau1sq) {
    .Call(`_lrcbart_forest_gvar_cpp`, draws, Xnew, tau0sq, tau1sq)
}

cg_montecarlo_cpp <- function(X, cutpoints, alpha, beta, nsim, maxdepth) {
    .Call(`_lrcbart_cg_montecarlo_cpp`, X, cutpoints, alpha, beta, nsim, maxdepth)
}

f_leaf_logmarg_cpp <- function(n1, n2, s1, s2, sig1sq, sig2sq, lam2) {
    .Call(`_lrcbart_f_leaf_logmarg_cpp`, n1, n2, s1, s2, sig1sq, sig2sq, lam2)
}

g_leaf_logmarg_cpp <- function(n1, s1, sig1sq, tau0sq, tau1sq, w) {
    .Call(`_lrcbart_g_leaf_logmarg_cpp`, n1, s1, sig1sq, tau0sq, tau1sq, w)
}

g_leaf_pspike_cpp <- function(n1, s1, sig1sq, tau0sq, tau1sq, w) {
    .Call(`_lrcbart_g_leaf_pspike_cpp`, n1, s1, sig1sq, tau0sq, tau1sq, w)
}

g_leaf_draw_cpp <- function(n1, s1, sig1sq, tau0sq, tau1sq, w, ndraw) {
    .Call(`_lrcbart_g_leaf_draw_cpp`, n1, s1, sig1sq, tau0sq, tau1sq, w, ndraw)
}

update_tau0_cpp <- function(theta, z, nu0, s0sq, tau1sq, ndraw) {
    .Call(`_lrcbart_update_tau0_cpp`, theta, z, nu0, s0sq, tau1sq, ndraw)
}

update_tau1_cpp <- function(theta, z, nu1, s1sq, tau0sq, ndraw) {
    .Call(`_lrcbart_update_tau1_cpp`, theta, z, nu1, s1sq, tau0sq, ndraw)
}

update_w_cpp <- function(z, aw, bw, ndraw) {
    .Call(`_lrcbart_update_w_cpp`, z, aw, bw, ndraw)
}

rtnorm_lower_cpp <- function(mu, sigma, a, n) {
    .Call(`_lrcbart_rtnorm_lower_cpp`, mu, sigma, a, n)
}

